import "./globals.css";
import { hindSiliguri } from "../fonts/nextFonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${hindSiliguri.variable}`}>
      <body className="font-hind-siliguri">{children}</body>
    </html>
  );
}
